### ISSUE TITLE
in libfdo_data, when we load an empty []byte - we are not getting nil we get a panic. 

### ISSUE THREAD

**Issue by Avielyo10** [fedora-iot/fido-device-onboard-rs#136]
in libfdo_data, when we load an empty []byte - voucher isn't nil, we get panic (before the check)
https://github.com/Avielyo10/edge-api/blob/fdo-client/pkg/services/ownershipvoucher/ownershipvoucher.go#L20

**Comment by runcom** [comment]
@Avielyo10 why are you using that? that's just a test script - you should borrow from that and just consume the API in your own Go code

**Comment by Avielyo10** [comment]
I created a wrapper around the lib, I'm not using the test script.
This function is critical for using the lib, shouldn't the lib provide the validation?

**Comment by Avielyo10** [comment]
@runcom https://github.com/Avielyo10/edge-api/blob/fdo-client/pkg/services/ownershipvoucher/ownershipvoucher.go#L20

**Comment by runcom** [comment]
> @runcom https://github.com/Avielyo10/edge-api/blob/fdo-client/pkg/services/ownershipvoucher/ownershipvoucher.go#L20

The library seems to provide guard around that (you can see the data check):

```rust
pub extern "C" fn fdo_ownershipvoucher_from_data(
    data: *const std::ffi::c_void,
    len: libc::size_t,
) -> *mut OwnershipVoucher {
    if data.is_null() {
        return null_mut();
    }
    let data = unsafe { slice::from_raw_parts(data as *const u8, len) };
    match OwnershipVoucher::deserialize_data(data) {
        Ok(voucher) => Box::into_raw(Box::new(voucher)),
        Err(_) => null_mut(),
    }
}
```

https://github.com/Avielyo10/edge-api/blob/fdo-client/pkg/services/ownershipvoucher/ownershipvoucher.go#L21 (defer comes after you check for `nil` also)

**Comment by Avielyo10** [comment]
Yes sorry, my bad lol

> defer comes after you check for `nil` also
Because in case I'm returning because of `nil` I want it to invoke

**Comment by Avielyo10** [comment]
panic will crush the server, unless I'll create `recover()` - a bit redundant IMO for this specific case

**Comment by puiterwijk** [comment]
Right, we really should not be panicking. Is there any chance you could share the panic, as @runcom mentioned, as that is a critical bug to us.

**Comment by puiterwijk** [comment]
Okay, reproduced it, and will make sure this gets fixed.

**Comment by Avielyo10** [comment]
thanks @puiterwijk
