### ISSUE TITLE
release 0.2.0

### ISSUE THREAD

**Issue by runcom** [fedora-iot/fido-device-onboard-rs#161]
now that kdf is fixed with https://github.com/fedora-iot/fido-device-onboard-rs/pull/160 should we go ahead and tag 0.2.0? @puiterwijk @nullr0ute (are we openssl complaint again?)

**Comment by nullr0ute** [comment]
:+1:

**Comment by runcom** [comment]
> (are we openssl complaint again?)

so nope, we'll cut a release I guess once we can build downstream as well

**Comment by puiterwijk** [comment]
This release is out.
