### ISSUE TITLE
Device Credential: semi-TPM

### ISSUE THREAD

**Issue by puiterwijk** [fedora-iot/fido-device-onboard-rs#200]
We can do a Device Credential system where the DC is in a filesystem, but it doesn't contain the private key (or HMAC key), but just the data used to ask the TPM to reproduce the key.

**Comment by mangelajo** [comment]
Yeah, that's how I found the tpm2 interface works mostly, it will provide you with a blob that can be passed back to the TPM module to give you the key. In a way that the tpm doesn't really need to store all the blobs for all generated keys, it just generates, encrypts, gives it to you, and you save it.

At least that's my overall understanding, I could be wrong.

**Comment by puiterwijk** [comment]
You're right with that, but our initial intent was to store everything in the TPM, including the rendezvous info and the data to derive the keys, so that there's nothing in the filesystem that could be accidentally erased before onboarding.
This ticket is to get a hybrid approach, awaiting some standardization processes.

**Comment by mangelajo** [comment]
All this also makes me think, off-chip TPMs are probably insecure, unless I'm missing some detail, for example, can't the secrets be dumped by just listening to the SPI bus? , I hope there's some additional crypto involved in those communications.

Of course, tpm "stored" PKs that will perform signatures/encryption in-tpm shouldn't be a big problem, as the final form of those is never leave the chip. The problem I see is if those keys leave the TPM to be used by the host...

**Comment by nullr0ute** [comment]
TPMs have the ability to encrypt traffic over the transport (SPI, I2C etc) if it's used properly so as such while they can't be insecure it doesn't mean they actually are if used properly.

**Comment by puiterwijk** [comment]
The keys I intended are the on-chip kind that never leave the TPM.
The TPM would just return the public key, and then during onboarding, it would regenerate the same key and sign things.
