### ISSUE TITLE
Add non-xattr (metadata file) support for Directory store driver

### ISSUE THREAD

**Issue by puiterwijk** [fedora-iot/fido-device-onboard-rs#288]
Right now, we only support extended attributes for metadata in the Store driver.
We should probably add support for metadata files to store metadata in, so that we can also run on system that do not support xattr.

**Comment by runcom** [comment]
I'm coming back on this as I'm kind of realizing what filesystem that we care about doesn't support xattrs cc @nullr0ute @7flying - do we know or anticipate such a filesystem being used?

**Comment by runcom** [comment]
I'm asking cause maybe the right thing to do here would be to just support metadata file w/o using xattr altogether (writing files should always be supported)

**Comment by mangelajo** [comment]
> I'm asking cause maybe the right thing to do here would be to just support metadata file w/o using xattr altogether (writing files should always be supported)

I agree, that's probably a good way to solve it so you don't have to support two different codepaths.

**Comment by nullr0ute** [comment]
I'm going to close this out, storing these on disk won't scale, we'll just go straight to a relational DB. It can always be reopened.
