### ISSUE TITLE
FDO cannot be used when creating RAW images

### ISSUE THREAD

**Issue by luisarizmendi** [fedora-iot/fido-device-onboard-rs#297]
In some cases, we need to fash (ARM) devices and for such a thing, creating RAW images (`composer-cli compose start-ostree ${blueprint} edge-raw-image`) is really useful.

At the same time, FDO cannot be used with this type of images, at least I found this error when I tried:

```
Starting FDO client...

fdo-client-linuxapp[1288]:  2022-07-20T09:04:02.230Z INFO  fdo_client_linuxapp > No usable device credential located, skipping Device Onboarding

/usr/bin/mv: cannot stat '/boot/device-credentials': No such file or directory

fdo-client-linuxapp.service: Deactivated successfully.

Finished FDO client.
```

I think FDO uses the `edge-simplified-installer` image type but I'm wondering if it will be extended to `edge-raw-image` too

Thanks.

**Comment by nullr0ute** [comment]
Ultimately the device credential should be stored in a TPM provided by the manufacturer so in that use case the device credential would just be retrieved from there. The current process requires simplified provisioning to be used when provisioning the OS which will work fine for any SystemReady devices. So as it stands ATM this is working as expected as there hasn't been a device credential generated and this needs to be done on a device device basis which isn't the case with a raw image that is dd:ed out to potentially a lot of devices.
