### ISSUE TITLE
Support for device identification other than serial number

### ISSUE THREAD

**Issue by jritter** [fedora-iot/fido-device-onboard-rs#333]
With the current implementation, matching a ownership voucher to a device only seems to be possible through the serial number. It would be great to be able to use other attributes, for instance the MAC address of the first interface.

In my experience, some vendors do a really bad job writing the serial number of their hardware to the SMBIOS, the possibility to find a uniquely identifiable MAC address for a device is much more likely.

**Comment by nullr0ute** [comment]
The problem with MACs is they're often changeable/movable.

**Comment by jritter** [comment]
Agree, but I'd argue that serial numbers are not perfect either. I'm currently working on a project with embedded computers where the manufacturer doesn't write the serial number into the SMBIOS. The MAC address of the embedded NIC would be a reasonable alternative in this case IMHO.

And if this was configurable the user can still choose which one is the better option for the use case at hand.

**Comment by nullr0ute** [comment]
> Agree, but I'd argue that serial numbers are not perfect either. I'm currently working on a project with embedded computers where the manufacturer doesn't write the serial number into the SMBIOS. The MAC address of the embedded NIC would be a reasonable alternative in this case IMHO.

Is the device using U-Boot in this case? The SystemReady-IR standard is working to ensure that is provided as part of certified devices.  

> And if this was configurable the user can still choose which one is the better option for the use case at hand.

How would the user choose that?

The "proper" fix to this is to use device credentials from a TPM2 or other similar HW security device.

Also can you link to where it's using serial # from  SMBIOS in the code?

**Comment by jritter** [comment]
> Is the device using U-Boot in this case? The SystemReady-IR standard is working to ensure that is provided as part of certified devices.

No, it is an Advantech x86_64 single board computer that unfortunately comes without a TPM. We are planning to deploy RHEL for Edge 9 on it. For booting we use UEFI and Grub.

> How would the user choose that?

I'd say in the configuration of the manufacturing server:
https://github.com/fedora-iot/fido-device-onboard-rs/blob/main/examples/config/manufacturing-server.yml#L26

> The "proper" fix to this is to use device credentials from a TPM2 or other similar HW security device.

In an ideal world I agree. Unfortunately we don't have that in our scenario. 

> Also can you link to where it's using serial # from SMBIOS in the code?
https://github.com/fedora-iot/fido-device-onboard-rs/blob/main/manufacturing-client/src/main.rs#L300-L302

I'll outline the big picture of the problem we are trying to solve: The idea is to ship pre-provisioned RHEL for Edge devices to places with cellular network connectivity only (untrusted). We would like them to connect to a VPN endpoint once they come online, but for that we need keys and device specific certificates. By the time they are provisioned they just have a credential and a ownership voucher. When deploying a particular device, somebody needs to pick up the device, read some sort of label on the box (and a MAC address is usually something that is printed on the box), and then assign the device to the "job" it needs to do. When the device comes online, it will then get the proper configuration and is able to do the job that got assigned to it. 

When running `fdo-owner-tool dump-ownership-voucher <ID>`, I see the serial number, in there, but it is unusable for us since the manufacturer doesn't populate it properly. If we had a MAC address it would be easy to make this link between a piece of hardware and a device that is trying to onboard.

I hope this makes sense.

**Comment by runcom** [comment]
```
If available, the device may include a serial number or other identifying mark from the hardware in this message, using DeviceMfgInfo. This is intended to help the manufacturing station to index FIDO Device Onboard information with other information available to the manufacturer. If no such information is available, DeviceMfgInfo is sent with a cbor null value.

The manufacturing station SHOULD be able to accept any legal value of DeviceMfgInfo, even if the value cannot be interpreted.
```
https://fidoalliance.org/specs/FDO/FIDO-Device-Onboard-RD-v1.1-20211214/FIDO-device-onboard-spec-v1.1-rd-20211214.html#DIAppStart

the FDO spec doesn't seem to mandate anything there, it can be a mac address from a nic, it can be a normal string as far as I can tell. At the end of the day, this is for indexing purposes for instance.
which nic? specify the nic? first one?

**Comment by runcom** [comment]
can you also provide the output of `sudo grep -r . /sys/class/dmi/id`

**Comment by DanielGurtne** [comment]
Yes normally we use nic1 as default. You can query with `grep . /sys/class/net/e*/address` to get all nic and the corresponding mac addresses. 
The output is as follows: 
`/sys/class/net/eth0/address:00:00:00:00:00:00`
`/sys/class/net/eth1/address:11:11:11:11:11:11`

The command `sudo grep -r . /sys/class/dmi/id` does not return a mac address

I hope this helps

**Comment by runcom** [comment]
@DanielGurtne indeed, I wasn't asking about mac address - grepping for "the first nic" is not optimal in terms of configuration too - what if a user wants the first nic but it's not an ethernet device? or what if they want wlan - this has to be specified but then you have to customize your manufacturing server to just one hardware type

**Comment by DanielGurtne** [comment]
@runcom sorry, I guess I didn't understand the context. 
The query also works with wlan interfaces combined (returns mac address as well as the name of the interface)...
`grep . /sys/class/net/{w,e}*/address`

Finally we reference the interface with the interface name in a kickstart file which as you said may differ depending on the hardware and interface type. And compare that identifier (mac address) with a CMDB.

I hope this helps

**Comment by runcom** [comment]
as an idea, the whole field could just be something like:

`SERIALNUMBER;NIC1;NIC2...NICn;OTHER_INFO`

**Comment by DanielGurtne** [comment]
@runcom yes that would be helpful to get the appropriate identifier. I think it would be important that the whole thing would be integrated as a key value pair so that it would be generic.

**Comment by runcom** [comment]
> @runcom yes that would be helpful to get the appropriate identifier. I think it would be important that the whole thing would be integrated as a key value pair so that it would be generic.

Yes, I've updated the snippet in my previous comment - I'd imagine anybody processing that would do something like `map.from_array(string.split(";"))`

**Comment by runcom** [comment]
just testing this out also, on my qemu machines I have no Device Info too:
```
[root@rhel9 ~]# cat /sys/devices/virtual/dmi/id/product_serial

[root@rhel9 ~]# cat /sys/devices/virtual/dmi/id/chassis_serial 

```

**Comment by sarmahaj** [comment]
@jritter @DanielGurtne this issue is fixed by https://github.com/fedora-iot/fido-device-onboard-rs/pull/396 and has been merged to main. Could you please verify on main branch and let us know your feed back.

**Comment by jritter** [comment]
Hi @sarmahaj, that's awesome news! Are there already any RPMs available that we can use?

**Comment by sarmahaj** [comment]
Hi @jritter As of now its only available on main branch of this repo.(not packaged yet) I hope you can manage to work with that!
