### ISSUE TITLE
set up docker test environment

### ISSUE THREAD

**Issue by muvarov** [fedora-iot/fido-device-onboard-rs#345]
Hello, I'm trying to run FIDO in some basis set up and see that client can be connected to server. I just followed docs but in some reason I get error. Does somebody have any clue what is missing?

1. git clone git@github.com:muvarov/docker-fido.git
2. docker build .
3. docker run -it <docker_hash) /bin/bash
4. /bin/fido_run.sh

` 2022-11-01T14:29:53.031Z ERROR fdo_client_linuxapp > Error performing TO1 with ServiceClient { protocol_version: Version1_1, base_url: "http://127.0.0.1:8082", client: Client { accepts: Accepts, proxies: [Proxy(System({}), None)], referer: true, default_headers: {"accept": "*/*"} }, authorization_token: None, encryption_keys: EncryptionKeys { cipher_suite: None, keys: None }, last_message_type: Some(Error), non_interoperable_kdf_required: Some(false) }
 2022-11-01T14:29:53.032Z ERROR fdo_client_linuxapp > Error Couldn't get TO1 from any Rendezvous server! getting usable To1d from rv_entry RendezvousInterpretedDirective { ip_addresses: Some([IPAddress(127.0.0.1)]), dns_name: None, port: 8082, server_certificate_hash: None, ca_certificate_hash: None, user_input: false, wifi_ssid: None, wifi_password: None, medium: None, protocol: Http, delay: 0, bypass: false }
`
Most of the configuration commands are in Dockerfile.

**Comment by muvarov** [comment]
I think I solved this. If somebody needs quick working environment you can use my Dockerfile. Closing this issue.

**Comment by nullr0ute** [comment]
> I think I solved this. If somebody needs quick working environment you can use my Dockerfile. Closing this issue.

Could you possibly include a PR to update the Docker file to include fixes for the issues you were seeing, or update/add docs for this please?

**Comment by muvarov** [comment]
@nullr0ute  Commit 15b8bee1b2926ae4a2b8aa58863326aac295278f of https://github.com/muvarov/docker-fido works well for me. At least client can do provisioning and connect to the server and download servers /etc/resolv.conf to /root/resolv.conf on the client.

**Comment by muvarov** [comment]
assuming you need to go inside container and run [fido_run.sh](https://github.com/muvarov/docker-fido/blob/master/fido_run.sh) script. (/bin/fido_run.sh).
