### ISSUE TITLE
Setup Packit for the repo

### ISSUE THREAD

**Issue by miabbott** [fedora-iot/fido-device-onboard-rs#435]
It would be excellent if we could configure [Packit](https://packit.dev/) on this repo, so that we could simplify the RPM packaging process.

I don't know if there are additional challenges around packaging Rust code + dependent crates in Fedora/CentOS Stream, but I hope we wouldn't be the first to take on that challenge.

(Having Packit configured would also help for requests like this: https://github.com/fedora-iot/fido-device-onboard-rs/issues/333#issuecomment-1450537680)

**Comment by nullr0ute** [comment]
There's a lot of challenges depending on how we end up dealing with it but it was already on my list. It also wouldn't help #333 until there's a tagged release with that feature in it.

**Comment by miabbott** [comment]
> It also wouldn't help #333 until there's a tagged release with that feature in it.

My intention here was that you could run `packit build` locally from `main` and get an RPM locally to test with.

**Comment by runcom** [comment]
> My intention here was that you could run `packit build` locally from `main` and get an RPM locally to test with.

notice we can already do `make rpm` locally and create an RPM (although if somebody needs it for say, c9s, they'll have to use a centos box to build it there) - I'm testing packit build locally too

**Comment by miabbott** [comment]
> notice we can already do `make rpm` locally and create an RPM (although if somebody needs it for say, c9s, they'll have to use a centos box to build it there) - I'm testing packit build locally too

I completely missed that ability; I didn't see it documented anywhere (but admittedly I didn't look very hard).
