### ISSUE TITLE
Using `StructuredDeviceInfo` as the `mfg_string_type` may break the X509 certificate standard's max length

### ISSUE THREAD

**Issue by 7flying** [fedora-iot/fido-device-onboard-rs#447]
When using the `StructuredDeviceInfo` as the `mfg_string_type` we might get a string that is longer than what the X509 certificate standard allows in its `CN` field, this causes an error in the Manufacturing Server, at the openssl `append_entry_by_text` call on `create_device_certificate`:

```
2023-03-10T13:11:14.902Z ERROR fdo_http_wrapper::server                 > Error occurred while processing message type DIAppStart: ErrorStack([Error { code: 109052055, library: "asn1 encoding routines", function: "ASN1_mbstring_ncopy", reason: "string too long", file: "crypto/asn1/a_mbstr.c", line: 106, data: "maxsize=64" }])
```

The max size of this field is: ` assert!(value.len() <= c_int::max_value() as usize);`

#### To take into account
- input fields that end up in the Manufacturing Server such as the serial/structured-device-info should be lenght-checked in the client if possible rather than wait until they are passed to the Manufacturing Server

**Comment by runcom** [comment]
let's use this to validate the fix here https://github.com/fedora-iot/fido-device-onboard-rs/pull/446 as it's indeed the culprit of the issue and write a feature/fix that makes that PR pass :)

**Comment by 7flying** [comment]
For reference:
```
CommonName ::= PrintableString (SIZE (1..ub-common-name-length))
ub-common-name-length INTEGER ::= 64
```
https://www.ietf.org/rfc/rfc2459.txt
