### ISSUE TITLE
OwnerSign To0d must be bstr instead of CBOR array

### ISSUE THREAD

**Issue by 7flying** [fedora-iot/fido-device-onboard-rs#496]
At `OwnerSign` (https://github.com/fedora-iot/fido-device-onboard-rs/blob/main/data-formats/src/messages/v11/to0.rs#L91):
```
pub struct OwnerSign {
    contents: ParsedArray<crate::cborparser::ParsedArraySize2>,

    cached_to0d: ByteBuf,
    cached_to1d: COSESign,
}
```
according to the spec this must be a bstr instead of cbor array (https://fidoalliance.org/specs/FDO/FIDO-Device-Onboard-RD-v1.1-20211214/FIDO-device-onboard-spec-v1.1-rd-20211214.html#rvblobsendmsg)

**Comment by puiterwijk** [comment]
Sorry, where do you see that?

What I see is:
```
TO0.OwnerSign = [
    bstr .cbor to0d,    ;; TO0 protocol parameters, not used in TO1
    to1d     ;; TO1 blob being provided from Owner
]
```

Which should be an Array of length 2 (i.e. `ParsedArray<ParsedArraySize2>`).

If I recall correctly, `ByteBuf` should match to a bstr.

The TO0d that is displayed in the referenced ticket would be the [v10 version](https://github.com/fedora-iot/fido-device-onboard-rs/blob/main/data-formats/src/messages/v10/to0.rs#L89), so I'm wondering if for some reason that is being used.
Because in v1.0 it *was* an array instead of bstr (that was the whole reason to switch to bstr).

**Comment by puiterwijk** [comment]
Upon rereading, I notice that the original issue was for the LF-Edge implementation.
I don't think this implementation has that same bug, as long as v1.1 is used correctly throughout the codebase.

**Comment by 7flying** [comment]
My understanding was that `crate::cborparser::ParsedArraySize2` should we replaced with a bstr, but I might be perfectly wrong.

**Comment by 7flying** [comment]
ah, I see, let me know if I got this right, so ` bstr .cbor to0d` is our ` cached_to0d: ByteBuf,` which is fine since it's a bstr, and then `contents: ParsedArray<crate::cborparser::ParsedArraySize2>` is something that we internally need to point to the two different fields in the struct, is that right?

**Comment by puiterwijk** [comment]
Exactly!
A `ParsedArray` is the system I'd come up with during the v1.0 era, where we needed to keep track of the original (non-decoded) byte stream to be able to verify signatures.

So, to map the [v11 code](https://github.com/fedora-iot/fido-device-onboard-rs/blob/main/data-formats/src/messages/v11/to0.rs#L89C1-L96C1) to the spec:

```rust
#[derive(Debug)]
// Map: TO0.OwnerSign = [
pub struct OwnerSign {
// A special thing to keep the original raw byte strings
    contents: ParsedArray<crate::cborparser::ParsedArraySize2>,

//     bstr .cbor to0d,    ;; TO0 protocol parameters, not used in TO1
    cached_to0d: ByteBuf,
//     to1d     ;; TO1 blob being provided from Owner
    cached_to1d: COSESign,
}
// Map: ]
```

This is being deserialised [here](https://github.com/fedora-iot/fido-device-onboard-rs/blob/main/data-formats/src/messages/v11/to0.rs#L102), by first deserialising the `ParsedArray<_>`, and then retrieving the two items from it to store (as "cached results").

**Comment by 7flying** [comment]
Gotcha! Fantastic, then we can close this since there is no issue.

Thanks for taking a look :pray:
