### ISSUE TITLE
Manufacturing server and client: check and sanitize Manufacturing Info

### ISSUE THREAD

**Issue by puiterwijk** [fedora-iot/fido-device-onboard-rs#54]
Right now, the Manufacturing Info string may contain newlines (for example with the Serial Number one).
This should be sanitized by the client (basically `str.trim()`).
The server should check that this string doesn't include whitespace or other "weird" characters.

**Comment by runcom** [comment]
basically just accept printable ASCII

**Comment by jnogol** [comment]
The idea is to add the sanitization in both serialization and deserialization of the Ownership Vouchers.

In the deserialization part it'd be adding one line after this one https://github.com/fedora-iot/fido-device-onboard-rs/blob/main/data-formats/src/ownershipvoucher.rs#L453

In pseudocode, it'd be
```
let cached_device_info = contents.get(OwnershipVoucherHeaderIndex::DeviceInfo as usize)?;
check_device_info(&cached_device_info)?;
```
And `check_device_info` has to be a function outside `impl Serializable for OwnershipVoucherHeader` as this function doesn't exist in the original implementation.

The definition of such function would be something like `fn check_device_info(device_info: &String) -> Result<()>` and, in pseudo code it'd be:
```
convert device_info to a vector of chars
iterate through this vector, comparing whether the char falls outside the acceptable ASCII range
if it does, return an error
if none of them do, return an empty `Ok(())`
```
